[package]
name = "estoc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.2.2", features = ["derive"] }
serde_json = "1.0.96"
gltf = "1.1.0"
nalgebra = "0.32.2"
rapier3d = "0.17.2"
